name = "meant-shop"
main = "worker.js"
compatibility_date = "2026-08-20"

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "meant-shop"
database_id = "REPLACE_WITH_D1_DATABASE_ID"
